services:
  redis:
    image: "redis:alpine"
    volumes:
      - redis-data:/data
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}", "--appendonly", "yes"]

  nestjs:
    image: eduardstroescu/ripple-link:latest #replace with your image name
    ports:
      - "3000:3000"
    environment:
      ACCESS_SECRET: ${ACCESS_SECRET}
      ADMIN_ID: ${ADMIN_ID}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      CLIENT_URL: ${CLIENT_URL}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
      MONGODB_URI: ${MONGODB_URI}
      PORT: ${PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_URL: ${REDIS_URL}
      REFRESH_SECRET: ${REFRESH_SECRET}
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis

volumes:
  redis-data:
